// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RefugioAnimales.Data;

#nullable disable

namespace RefugioAnimales.Migrations
{
    [DbContext(typeof(RefugioContext))]
    [Migration("20251119191254_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RefugioAnimales.Models.Adoptante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Adoptantes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "maria@example.com",
                            FechaAlta = new DateTime(2025, 8, 19, 20, 12, 50, 891, DateTimeKind.Local).AddTicks(7574),
                            Nombre = "María García",
                            Telefono = "666777888"
                        },
                        new
                        {
                            Id = 2,
                            Email = "juan@example.com",
                            FechaAlta = new DateTime(2025, 10, 19, 20, 12, 50, 891, DateTimeKind.Local).AddTicks(7581),
                            Nombre = "Juan Pérez",
                            Telefono = "666111222"
                        });
                });

            modelBuilder.Entity("RefugioAnimales.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdoptanteId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaAdopcion")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("FotoContenido")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FotoMimeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AdoptanteId");

                    b.ToTable("Animales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Energética y cariñosa.",
                            Edad = 3,
                            Especie = "Perro",
                            Estado = "Disponible",
                            Nombre = "Luna"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Un gato cariñoso y tranquilo.",
                            Edad = 2,
                            Especie = "Gato",
                            Estado = "Disponible",
                            Nombre = "Milo"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Una perra enérgica y leal.",
                            Edad = 5,
                            Especie = "Perro",
                            Estado = "Disponible",
                            Nombre = "Bella"
                        });
                });

            modelBuilder.Entity("RefugioAnimales.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NombreUsuario = "admin",
                            PasswordHash = "Z2YeM5fJHwon8tdLGVTVwzJFH2Wv9jJ2vVWPu+0VVdY=",
                            Rol = "Admin",
                            Salt = "u1snxLW/luPKmyOTCfzw3/RY7zwN/IDaAnDCIZ9r9nA="
                        });
                });

            modelBuilder.Entity("RefugioAnimales.Models.Animal", b =>
                {
                    b.HasOne("RefugioAnimales.Models.Adoptante", "Adoptante")
                        .WithMany("Animales")
                        .HasForeignKey("AdoptanteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Adoptante");
                });

            modelBuilder.Entity("RefugioAnimales.Models.Adoptante", b =>
                {
                    b.Navigation("Animales");
                });
#pragma warning restore 612, 618
        }
    }
}
